In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Matplotlib is building the font cache; this may take a moment.

In [8]:
df = pd.read_csv(r"D:\AIML_MSIS\Applied Machine Learning\Lab_programs\August_18\Groceries_dataset.csv")
df

       Member_number        Date        itemDescription
0               1808  21-07-2015         tropical fruit
1               2552  05-01-2015             whole milk
2               2300  19-09-2015              pip fruit
3               1187  12-12-2015       other vegetables
4               3037  01-02-2015             whole milk
...              ...         ...                    ...
38760           4471  08-10-2014          sliced cheese
38761           2022  23-02-2014                  candy
38762           1097  16-04-2014               cake bar
38763           1510  03-12-2014  fruit/vegetable juice
38764           1521  26-12-2014               cat food

[38765 rows x 3 columns]

In [ ]:

df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y'
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
x = df[['Member_number', 'Year', 'Month', 'Day']].values

In [9]:
df.shape

(38765, 3)

In [10]:
df.columns

Index(['Member_number', 'Date', 'itemDescription'], dtype='str')

In [11]:
df.dtypes

Member_number      int64
Date                 str
itemDescription      str
dtype: object

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 38765 entries, 0 to 38764
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Member_number    38765 non-null  int64
 1   Date             38765 non-null  str
 2   itemDescription  38765 non-null  str
dtypes: int64(1), str(2)
memory usage: 908.7 KB

In [13]:
df.describe()

       Member_number
count   38765.000000
mean     3003.641868
std      1153.611031
min      1000.000000
25%      2002.000000
50%      3005.000000
75%      4007.000000
max      5000.000000

In [14]:
df.isnull().sum()

Member_number      0
Date               0
itemDescription    0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(759)

In [29]:
#split indepedent variable
#df
#x=df.iloc[:, :-1].values
#x

df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
x = df[['Member_number', 'Year', 'Month', 'Day']].values

In [31]:
#dpilt dependent variable
y=df.iloc[:,2].values
y

<StringArray>
[          'tropical fruit',               'whole milk',
                'pip fruit',         'other vegetables',
               'whole milk',               'rolls/buns',
         'other vegetables',               'pot plants',
               'whole milk',           'tropical fruit',
 ...
            'bottled water',    'fruit/vegetable juice',
               'rolls/buns', 'long life bakery product',
                      'oil',            'sliced cheese',
                    'candy',                 'cake bar',
    'fruit/vegetable juice',                 'cat food']
Length: 38765, dtype: str

In [32]:
from sklearn.preprocessing import LabelEncoder

#Encoding the Dependent variable

labelencoder_y =LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([156, 164, 109, ...,  17,  64,  24], shape=(38765,))

In [33]:
#split the data into training and testing
#test_size=0.2 -> training 80%, testing %20
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=45)
#X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [34]:
X_test
#X_test.astype(int)

array([[2162, 2015,    6,   19],
       [1343, 2014,    2,    7],
       [1426, 2014,    3,   20],
       ...,
       [2930, 2014,    4,    3],
       [2289, 2014,    7,    3],
       [3834, 2014,    3,   21]], shape=(7753, 4))

In [35]:
X_train

array([[4037, 2015,   12,   29],
       [4832, 2014,   12,   18],
       [3573, 2014,   10,   13],
       ...,
       [4383, 2014,    6,    3],
       [4205, 2015,    1,   29],
       [4634, 2015,    2,   26]], shape=(31012, 4))

In [36]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [37]:
X_test

array([[-0.73553661,  0.94306031, -0.14479709,  0.36640418],
       [-1.44479206, -1.06037758, -1.31471759, -0.9947106 ],
       [-1.37291391, -1.06037758, -1.02223746,  0.47983041],
       ...,
       [-0.07044726, -1.06037758, -0.72975734, -1.44841553],
       [-0.62555439, -1.06037758,  0.14768303, -1.44841553],
       [ 0.71241834, -1.06037758, -1.02223746,  0.59325664]],
      shape=(7753, 4))

In [38]:
X_train

array([[ 0.8882167 ,  0.94306031,  1.61008366,  1.5006665 ],
       [ 1.57668811, -1.06037758,  1.61008366,  0.25297795],
       [ 0.48639188, -1.06037758,  1.02512341, -0.31415321],
       ...,
       [ 1.18785331, -1.06037758, -0.14479709, -1.44841553],
       [ 1.033705  ,  0.94306031, -1.60719771,  1.5006665 ],
       [ 1.40521976,  0.94306031, -1.31471759,  1.1603878 ]],
      shape=(31012, 4))